In [1]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv('USGovtRevCollect_20041001_20231227.csv')  
df

Record Date Electronic Category Description Channel Type Description  \
0      2023-12-27                  Non-Electronic                     Mail   
1      2023-12-27           Electronic Settlement   Over-the-Counter (OTC)   
2      2023-12-27                  Non-Electronic   Over-the-Counter (OTC)   
3      2023-12-27           Fully Electronic - FS   Over-the-Counter (OTC)   
4      2023-12-27          Fully Electronic - All                     Bank   
...           ...                             ...                      ...   
81243  2004-10-01          Fully Electronic - All                     Bank   
81244  2004-10-01                  Non-Electronic                     Bank   
81245  2004-10-01          Fully Electronic - All                 Internet   
81246  2004-10-01           Fully Electronic - FS   Over-the-Counter (OTC)   
81247  2004-10-01          Fully Electronic - All                     Mail   

      Tax Category Description  Net Collections Amount  \
0                      Non-Tax            7.269500e+02   
1                      Non-Tax            2.431048e+05   
2                      Non-Tax            9.395110e+06   
3                  IRS Non-Tax            4.824105e+04   
4                      IRS Tax            2.905820e+03   
...                        ...                     ...   
81243                  IRS Tax            4.838831e+09   
81244                  Non-Tax            2.114361e+06   
81245                  Non-Tax            1.183413e+07   
81246                  Non-Tax            1.921165e+06   
81247                  IRS Tax            1.298839e+06   

       Electronic Category ID  Channel Type ID  Tax Category ID  \
0                           4                2                1   
1                           3                1                1   
2                           4                1                1   
3                           2                1                2   
4                           1                5                3   
...                       ...              ...              ...   
81243                       1                5                3   
81244                       4                5                1   
81245                       1                3                1   
81246                       2                1                1   
81247                       1                2                3   

       Source Line Number  Fiscal Year  Fiscal Quarter Number  Calendar Year  \
0                       1         2024                      1           2023   
1                       2         2024                      1           2023   
2                       3         2024                      1           2023   
3                       4         2024                      1           2023   
4                       5         2024                      1           2023   
...                   ...          ...                    ...            ...   
81243                  12         2005                      1           2004   
81244                   1         2005                      1           2004   
81245                   2         2005                      1           2004   
81246                   3         2005                      1           2004   
81247                  13         2005                      1           2004   

       Calendar Quarter Number  Calendar Month Number  Calendar Day Number  
0                            4                     12                   27  
1                            4                     12                   27  
2                            4                     12                   27  
3                            4                     12                   27  
4                            4                     12                   27  
...                        ...                    ...                  ...  
81243                        4                     10              

In [64]:
#81248 rows of data and 15 columns
df.shape

(81248, 15)

In [10]:
df.dtypes

Record Date                         object
Electronic Category Description     object
Channel Type Description            object
Tax Category Description            object
Net Collections Amount             float64
Electronic Category ID               int64
Channel Type ID                      int64
Tax Category ID                      int64
Source Line Number                   int64
Fiscal Year                          int64
Fiscal Quarter Number                int64
Calendar Year                        int64
Calendar Quarter Number              int64
Calendar Month Number                int64
Calendar Day Number                  int64
dtype: object

In [27]:
#Converting Record Date column to datetime objects.
df['Record Date'] = pd.to_datetime(df['Record Date'])

In [28]:
df

Record Date Electronic Category Description Channel Type Description  \
0      2023-12-27                  Non-Electronic                     Mail   
1      2023-12-27           Electronic Settlement   Over-the-Counter (OTC)   
2      2023-12-27                  Non-Electronic   Over-the-Counter (OTC)   
3      2023-12-27           Fully Electronic - FS   Over-the-Counter (OTC)   
4      2023-12-27          Fully Electronic - All                     Bank   
...           ...                             ...                      ...   
81243  2004-10-01          Fully Electronic - All                     Bank   
81244  2004-10-01                  Non-Electronic                     Bank   
81245  2004-10-01          Fully Electronic - All                 Internet   
81246  2004-10-01           Fully Electronic - FS   Over-the-Counter (OTC)   
81247  2004-10-01          Fully Electronic - All                     Mail   

      Tax Category Description  Net Collections Amount  \
0                      Non-Tax            7.269500e+02   
1                      Non-Tax            2.431048e+05   
2                      Non-Tax            9.395110e+06   
3                  IRS Non-Tax            4.824105e+04   
4                      IRS Tax            2.905820e+03   
...                        ...                     ...   
81243                  IRS Tax            4.838831e+09   
81244                  Non-Tax            2.114361e+06   
81245                  Non-Tax            1.183413e+07   
81246                  Non-Tax            1.921165e+06   
81247                  IRS Tax            1.298839e+06   

       Electronic Category ID  Channel Type ID  Tax Category ID  \
0                           4                2                1   
1                           3                1                1   
2                           4                1                1   
3                           2                1                2   
4                           1                5                3   
...                       ...              ...              ...   
81243                       1                5                3   
81244                       4                5                1   
81245                       1                3                1   
81246                       2                1                1   
81247                       1                2                3   

       Source Line Number  Fiscal Year  Fiscal Quarter Number  Calendar Year  \
0                       1         2024                      1           2023   
1                       2         2024                      1           2023   
2                       3         2024                      1           2023   
3                       4         2024                      1           2023   
4                       5         2024                      1           2023   
...                   ...          ...                    ...            ...   
81243                  12         2005                      1           2004   
81244                   1         2005                      1           2004   
81245                   2         2005                      1           2004   
81246                   3         2005                      1           2004   
81247                  13         2005                      1           2004   

       Calendar Quarter Number  Calendar Month Number  Calendar Day Number  
0                            4                     12                   27  
1                            4                     12                   27  
2                            4                     12                   27  
3                            4                     12                   27  
4                            4                     12                   27  
...                        ...                    ...                  ...  
81243                        4                     10              

In [31]:
df['Electronic Category Description'].unique()

array(['Non-Electronic', 'Electronic Settlement', 'Fully Electronic - FS',
       'Fully Electronic - All'], dtype=object)

In [32]:
df['Channel Type Description'].unique()

array(['Mail', 'Over-the-Counter (OTC)', 'Bank', 'Internet', 'Other'],
      dtype=object)

In [42]:
df['Tax Category Description'].unique()

array(['Non-Tax', 'IRS Non-Tax', 'IRS Tax'], dtype=object)

In [46]:
df['Electronic Category ID'].unique()

array([4, 3, 2, 1], dtype=int64)

In [53]:
df['Channel Type ID'].unique()

array([2, 1, 5, 3, 7], dtype=int64)

In [54]:
df['Tax Category ID'].unique()

array([1, 2, 3], dtype=int64)

In [55]:
df['Source Line Number'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23], dtype=int64)

In [57]:
df['Fiscal Year'].unique()

array([2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014,
       2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005], dtype=int64)

In [58]:
df['Calendar Year'].unique()

array([2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013,
       2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004], dtype=int64)

In [65]:
#No missing data
df.isnull().values.any()

False

In [68]:
#4834 unique days of records
df.groupby('Record Date').count()

Electronic Category Description  Channel Type Description  \
Record Date                                                              
2004-10-01                                17                        17   
2004-10-04                                16                        16   
2004-10-05                                17                        17   
2004-10-06                                17                        17   
2004-10-07                                16                        16   
...                                      ...                       ...   
2023-12-20                                15                        15   
2023-12-21                                14                        14   
2023-12-22                                15                        15   
2023-12-26                                14                        14   
2023-12-27                                15                        15   

             Tax Category Description  Net Collections Amount  \
Record Date                                                     
2004-10-01                         17                      17   
2004-10-04                         16                      16   
2004-10-05                         17                      17   
2004-10-06                         17                      17   
2004-10-07                         16                      16   
...                               ...                     ...   
2023-12-20                         15                      15   
2023-12-21                         14                      14   
2023-12-22                         15                      15   
2023-12-26                         14                      14   
2023-12-27                         15                      15   

             Electronic Category ID  Channel Type ID  Tax Category ID  \
Record Date                                                             
2004-10-01                       17               17               17   
2004-10-04                       16               16               16   
2004-10-05                       17               17               17   
2004-10-06                       17               17               17   
2004-10-07                       16               16               16   
...                             ...              ...              ...   
2023-12-20                       15               15               15   
2023-12-21                       14               14               14   
2023-12-22                       15               15               15   
2023-12-26                       14               14               14   
2023-12-27                       15               15               15   

             Source Line Number  Fiscal Year  Fiscal Quarter Number  \
Record Date                                                           
2004-10-01                   17           17                     17   
2004-10-04                   16           16                     16   
2004-10-05                   17           17                     17   
2004-10-06                   17           17                     17   
2004-10-07                   16           16                     16   
...                         ...          ...                    ...   
2023-12-20                   15           15                     15   
2023-12-21                   14           14                     14   
2023-12-22                   15           15                     15   
2023-12-26                   14           14                     14   
2023-12-27                   15           15                     15   

             Calendar Year  Calendar Quarter Number  Calendar Month Number  \
Record Date                                                                  
2004-10-01              17                       17                     17   
2004-10-04              16                       16                     16   
2004-10-05        

In [70]:
df

Record Date Electronic Category Description Channel Type Description  \
0      2023-12-27                  Non-Electronic                     Mail   
1      2023-12-27           Electronic Settlement   Over-the-Counter (OTC)   
2      2023-12-27                  Non-Electronic   Over-the-Counter (OTC)   
3      2023-12-27           Fully Electronic - FS   Over-the-Counter (OTC)   
4      2023-12-27          Fully Electronic - All                     Bank   
...           ...                             ...                      ...   
81243  2004-10-01          Fully Electronic - All                     Bank   
81244  2004-10-01                  Non-Electronic                     Bank   
81245  2004-10-01          Fully Electronic - All                 Internet   
81246  2004-10-01           Fully Electronic - FS   Over-the-Counter (OTC)   
81247  2004-10-01          Fully Electronic - All                     Mail   

      Tax Category Description  Net Collections Amount  \
0                      Non-Tax            7.269500e+02   
1                      Non-Tax            2.431048e+05   
2                      Non-Tax            9.395110e+06   
3                  IRS Non-Tax            4.824105e+04   
4                      IRS Tax            2.905820e+03   
...                        ...                     ...   
81243                  IRS Tax            4.838831e+09   
81244                  Non-Tax            2.114361e+06   
81245                  Non-Tax            1.183413e+07   
81246                  Non-Tax            1.921165e+06   
81247                  IRS Tax            1.298839e+06   

       Electronic Category ID  Channel Type ID  Tax Category ID  \
0                           4                2                1   
1                           3                1                1   
2                           4                1                1   
3                           2                1                2   
4                           1                5                3   
...                       ...              ...              ...   
81243                       1                5                3   
81244                       4                5                1   
81245                       1                3                1   
81246                       2                1                1   
81247                       1                2                3   

       Source Line Number  Fiscal Year  Fiscal Quarter Number  Calendar Year  \
0                       1         2024                      1           2023   
1                       2         2024                      1           2023   
2                       3         2024                      1           2023   
3                       4         2024                      1           2023   
4                       5         2024                      1           2023   
...                   ...          ...                    ...            ...   
81243                  12         2005                      1           2004   
81244                   1         2005                      1           2004   
81245                   2         2005                      1           2004   
81246                   3         2005                      1           2004   
81247                  13         2005                      1           2004   

       Calendar Quarter Number  Calendar Month Number  Calendar Day Number  
0                            4                     12                   27  
1                            4                     12                   27  
2                            4                     12                   27  
3                            4                     12                   27  
4                            4                     12                   27  
...                        ...                    ...                  ...  
81243                        4                     10              

In [74]:
df.groupby('Electronic Category Description').count()[['Record Date']].rename(columns = {'Record Date': 'Count'})

Count
Electronic Category Description       
Electronic Settlement            12466
Fully Electronic - All           31609
Fully Electronic - FS            14129
Non-Electronic                   23044

In [76]:
df.groupby('Channel Type Description').count()[['Record Date']].rename(columns = {'Record Date': 'Count'})

Count
Channel Type Description       
Bank                      12443
Internet                  13911
Mail                      20345
Other                        66
Over-the-Counter (OTC)    34483

In [77]:
df.groupby('Tax Category Description').count()[['Record Date']].rename(columns = {'Record Date': 'Count'})

Count
Tax Category Description       
IRS Non-Tax               18545
IRS Tax                   24843
Non-Tax                   37860

In [78]:
df.groupby('Fiscal Year').count()[['Record Date']].rename(columns = {'Record Date': 'Count'})

Count
Fiscal Year       
2005          4701
2006          5003
2007          5255
2008          4810
2009          4546
2010          4449
2011          4742
2012          4656
2013          4497
2014          4171
2015          4043
2016          4051
2017          3920
2018          3842
2019          3801
2020          3512
2021          3461
2022          3454
2023          3465
2024           869

In [80]:
df.groupby('Fiscal Year').sum()[['Net Collections Amount']]

Net Collections Amount
Fiscal Year                        
2005                   2.651425e+12
2006                   2.921450e+12
2007                   3.109482e+12
2008                   3.191062e+12
2009                   2.855280e+12
2010                   2.935275e+12
2011                   3.062801e+12
2012                   3.158251e+12
2013                   3.562188e+12
2014                   3.734363e+12
2015                   3.980977e+12
2016                   3.963279e+12
2017                   4.101233e+12
2018                   4.151205e+12
2019                   4.262253e+12
2020                   4.242796e+12
2021                   4.909410e+12
2022                   5.758646e+12
2023                   5.466726e+12
2024                   1.268031e+12

In [82]:
df.groupby('Electronic Category Description').sum()[['Net Collections Amount']]

Net Collections Amount
Electronic Category Description                        
Electronic Settlement                      5.683999e+12
Fully Electronic - All                     6.248116e+13
Fully Electronic - FS                      6.513066e+11
Non-Electronic                             4.469666e+12

In [84]:
df.groupby('Channel Type Description').sum()[['Net Collections Amount']]

Net Collections Amount
Channel Type Description                        
Bank                                1.574290e+13
Internet                            4.660688e+13
Mail                                8.189791e+12
Other                               2.569657e+07
Over-the-Counter (OTC)              2.746536e+12

In [83]:
df.groupby('Tax Category Description').sum()[['Net Collections Amount']]

Net Collections Amount
Tax Category Description                        
IRS Non-Tax                         2.529981e+09
IRS Tax                             6.110596e+13
Non-Tax                             1.217764e+13